spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: willamhuamansaavedra13@gmail.com
    password: kkls wwld icvh rmhh
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false

  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
